### ISSUE TITLE
How to send local image in embeds?

### ISSUE THREAD

**Issue by Jinhao61** [10mohi6/discord-webhook-python#4]
Hi!
From the examples given, we can send images inside embeds with:
`"image": {"url": "https://picsum.photos/400/300"`

Is there a way to send not via url, but local file path?

**Comment by 10mohi6** [comment]
Try the code below
```python
discord.post(
    file={
        "file1": open("tests/file1.png", "rb"),
        "file2": open("tests/file2.jpeg", "rb"),
    },
    embeds=[
        {
            "title": "Embed Title",
            "image": {"url": "attachment://file1.png"},
            "thumbnail": {"url": "attachment://file2.jpeg"},
        }
    ],
)
```

**Comment by Jinhao61** [comment]
I tried it just now, I found that:
```
    file={
        "file1": open("tests/file1.png", "rb"),
        "file2": open("tests/file2.jpeg", "rb"),
    },
```
is completing the task of sending the local image, and adding or removing the "image" and "thumbnail" don't effect the layout, i.e. the two images always appear on their own right above the embed box, instead of at the "image" or "thumbnail" position. Screenshot attached.
![2022-05-17@20 02](https://user-images.githubusercontent.com/101698933/168948704-435759bb-71bf-4b70-9dc3-b30fd8d0cfcc.png)
.

**Comment by 10mohi6** [comment]
Sorry but no problem in my environment

```python
discord.post(
    file={
        "file1": open("tests/file1.png", "rb"),
        "file2": open("tests/file2.jpeg", "rb"),
    },
    # embeds=[
    #     {
    #         "title": "Embed Title",
    #         "image": {"url": "attachment://file1.png"},
    #         "thumbnail": {"url": "attachment://file2.jpeg"},
    #     }
    # ],
)
```
![FireShot Capture 316 - general - discord com](https://user-images.githubusercontent.com/38859131/168955504-6285bda5-3210-4999-8d4c-a0ffd7bbd827.png)

```python
discord.post(
    file={
        "file1": open("tests/file1.png", "rb"),
        "file2": open("tests/file2.jpeg", "rb"),
    },
    embeds=[
        {
            "title": "Embed Title",
            "image": {"url": "attachment://file1.png"},
            "thumbnail": {"url": "attachment://file2.jpeg"},
        }
    ],
)
```
![FireShot Capture 315 - general - discord com](https://user-images.githubusercontent.com/38859131/168955636-c793cf63-98df-43a8-951b-b72367f93679.png)

**Comment by Jinhao61** [comment]
Still could not even using the same code as yours, I settled with it not being inside the embed. Thank you tho, appreciate it!
